name: NPM Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        id: release
        uses: googleapis/release-please-action@v4
        # with:
        #   path: "pkcg"
        #   release-type: "node"
        #   manifest-file: "pkg/package.json"
