name: publish-npm-manual

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "actually publish"
        required: true
        default: false
        type: boolean

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup rust
        uses: dtolnay/rust-toolchain@1a3a6d54512beeaffd394f8d516ca16f2c506a20 # 1.97

      - name: Install wasm-pack
        run: |
          VERSION=$(cargo metadata --manifest-path tools/Cargo.toml --format-version 1 --no-deps \
            | jq -r '.packages[0].dependencies[] | select(.name=="wasm-pack") | .req' \
            | sed 's/^=//')
          cargo install wasm-pack --version "$VERSION" --locked

      - name: Build
        run: wasm-pack build --release --target web --scope mdn

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: ".nvmrc"
          package-manager-cache: false

      - name: Test Publish
        if: ${{ ! inputs.publish }}
        working-directory: ./pkg
        run: npm publish --access public --dry-run

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: ./pkg
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
