name: publish-npm-manual

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "actually publish"
        required: true
        default: false
        type: boolean

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo install wasm-pack && wasm-pack build --release --target web --scope mdn

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: "./pkg/package.json"

      - name: Test Publish
        if: ${{ ! inputs.publish }}
        working-directory: ./pkg
        run: npm publish --access public --dry-run

      - name: Publish
        if: ${{ inputs.publish }}
        working-directory: ./pkg
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
